accounts/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from . import (
    views as acc_views,
    forms as acc_form
)

app_name = 'accounts'

urlpatterns = [
    path('signup/', acc_views.SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(
            template_name='accounts/login.html',
            authentication_form=acc_form.UserLoginForm
            ),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

shortener/urls.py
from django.urls import path
from . import views as shortener_views


urlpatterns = [
    path('', shortener_views.base, name="home"),
    path('about', shortener_views.about, name="about"),
    path('create', shortener_views.create, name="create"),
    path(
        'createurl',
         shortener_views.create_user_url,
         name="create_user_url"
         ),
    path('go/<str:pk>', shortener_views.go, name="go"),
    path('g/<str:pk>', shortener_views.user_url_go, name="user_url_go"),
]

url_shortner/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls')),
    path('account/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models
from django.contrib.auth import models


# user model
class User(models.User, models.PermissionsMixin):

    def __str__(self):
        return f"@{self.username}"

shortener/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Url(models.Model):
    link = models.CharField(max_length=20000)
    uuid = models.CharField(max_length=10)

    def __str__(self):
        return f"<UUID: {self.uuid}>"


class UserUrl(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    link = models.CharField(max_length=20000)
    uuid = models.CharField(max_length=10)

    def __str__(self):
        return f"<{self.user} Url>"

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# new user create form
class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control bg-white border-left-0 border-md'
        self.fields['username'].widget.attrs['id'] = 'username'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'

        self.fields['first_name'].widget.attrs['class'] = 'form-control bg-white border-left-0 border-md'
        self.fields['first_name'].widget.attrs['id'] = 'first_name'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'

        self.fields['last_name'].widget.attrs['class'] = 'form-control bg-white border-left-0 border-md'
        self.fields['last_name'].widget.attrs['id'] = 'last_name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'

        self.fields['email'].widget.attrs['class'] = 'form-control bg-white border-left-0 border-md'
        self.fields['email'].widget.attrs['id'] = 'email'
        self.fields['email'].widget.attrs['placeholder'] = 'Email Address'

        self.fields['password1'].widget.attrs['class'] = 'form-control bg-white border-left-0 border-md'
        self.fields['password1'].widget.attrs['id'] = 'password'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'

        self.fields['password2'].widget.attrs['class'] = 'form-control bg-white border-left-0 border-md'
        self.fields['password2'].widget.attrs['id'] = 'passwordConfirmation'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'


# login form
class UserLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control bg-white border-left-0 border-md'
        self.fields['username'].widget.attrs['id'] = 'username'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'

        self.fields['password'].widget.attrs['class'] = 'form-control bg-white border-left-0 border-md'
        self.fields['password'].widget.attrs['id'] = 'password'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy

from . import forms as acc_form


class SignupView(CreateView):
    form_class = acc_form.UserCreateForm
    success_url = reverse_lazy("accounts:login")
    template_name = "accounts/signup.html"

shortener/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

import uuid

from .models import Url, UserUrl


# Create your views here.
def base(request):
    ctx = dict()
    if request.user.is_authenticated:
        current_user = request.user
        # filter out current user created urls
        user_urls = UserUrl.objects.filter(user=current_user)

        total_user_url_links = [i + 1 for i in range(user_urls.count())]
        ctx['user_sl'] = iter(total_user_url_links)
        ctx['user_urls'] = user_urls
    else:
        # for anonymous user
        new_urls = Url.objects.all()
        total_links = [i + 1 for i in range(new_urls.count())]
        ctx['sl'] = iter(total_links)
        ctx['urls'] = new_urls

    return render(request, 'base.html', context=ctx)


def create(request):
    if request.method == 'POST':
        url = request.POST['link']
        uid = str(uuid.uuid4())[:5]  # generate unique id of length 5
        new_url = Url(link=url, uuid=uid)
        new_url.save()
        return HttpResponse(uid)


def go(request, pk):
    url_details = Url.objects.get(uuid=pk)
    link = url_details.link
    if link[:8] == 'https://' or link[:7] == 'http://':
        return redirect(link)
    else:
        return redirect(f'https://{url_details.link}')


def create_user_url(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            user = request.user # fetch user obj from request
            link = request.POST['link']
            uid = str(uuid.uuid4())[:5]  # generate unique id of length 5
            new_url = UserUrl(user=user, link=link, uuid=uid)
            new_url.save()
            return HttpResponse(uid)


@login_required
def user_url_go(request, pk):
    url_details = UserUrl.objects.get(uuid=pk)
    link = url_details.link
    print(f"\n--------debug--------\n")
    print(f"\n{link}\n")
    if link[:8] == 'https://' or link[:7] == 'http://':
        return redirect(link)
    else:
        return redirect(f'https://{url_details.link}')


def about(request):
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'accounts/signup.html' %}

{% block pg_title %}
    <!-- Page Title -->
    <title>Log in | TyniURL</title>
{% endblock %}

{% block subject %}
    <h1>Welcome Back</h1>
    <p class="font-italic text-muted mb-0">Log in and Get Unlimited Access</p>
{% endblock %}

{% block form %}
    <!-- Login Form -->
    <form action="{% url 'accounts:login' %}" method="POST" id="login_form" name="login_form">
        {% csrf_token %}
        <div class="row">
            <!-- username -->
            <div class="input-group col-lg-12 mt-4">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-white px-4 border-md border-right-0">
                        <i class="fas fa-at text-muted"></i>
                    </span>
                </div>
                {{ form.username }}
            </div>

            <!-- Password -->
            <div class="input-group col-lg-12 mt-4">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-white px-4 border-md border-right-0">
                        <i class="fa fa-lock text-muted"></i>
                    </span>
                </div>
                {{ form.password }}
            </div>
            {% if form.errors %}
                <div class="input-group col-lg-12 mt-2 ml-1">
                    <span class="form-not-valid">
                        <small>Username or Password is incorrect, please try again.</small>
                    </span>
                </div>
            {% endif %}

            <!-- Submit Button -->
            <div class="form-group col-lg-12 mx-auto mt-4">
                <button for="signup_form" type="submit" class="font-weight-bold btn btn-primary btn-block py-2 btn-tyni">Log in</button>
            </div>
            <!-- Already Registered -->
            <div class="text-center w-100">
                <p class="text-muted font-weight-bold">Not Registered? <a href="{% url 'accounts:signup' %}" class="text-primary ml-2">Sign Up</a></p>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'images/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- <div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->

    <!-- favicon ends here -->
    {% block pg_title %} <title>Sign Up | TyniURL</title> {% endblock %}
    <!-- bootstrap@4.3 css cdn -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- fontawesome cdn -->
    <script src="https://kit.fontawesome.com/5fe89886dc.js" crossorigin="anonymous"></script>

    <!-- jQuery CDN -->
    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>

    <!--  custom css  -->
    <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
</head>
<body>

<!-- Navbar-->
<header class="header">
    <nav class="navbar navbar-expand-lg navbar-light py-3">
        <div class="container">
            <!-- Navbar Brand -->
            <a href="/" class="navbar-brand">
                <span class="brand-name">TyniURL</span>
            </a>
        </div>
    </nav>
</header>


<div class="container">
    <div class="row py-5 mt-4 align-items-center">
        <div class="col-md-5 pr-lg-5 mb-5 mb-md-0">
            <img src="{% static 'accounts/images/theme/referral.svg' %}" width="300" alt="" class="img-fluid mb-3 d-none d-md-block">
            {% block subject %}
            <h1>Create an Account</h1>
            <p class="font-italic text-muted mb-0">Create and Get Unlimited Access to Shorted Linkes</p>
            {% endblock %}
        </div>

        <div class="col-md-7 col-lg-6 ml-auto">
            <!-- Sign Up Form -->
            {% block form %}
            <form action="" method="POST" id="signup_form" name="signup_form">
                {% csrf_token %}
                <div class="row">

                    <!-- User Name -->
                    <div class="input-group col-lg-12 mt-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fas fa-at text-muted"></i>
                            </span>
                        </div>
<!--                       <input id="username" type="text" name="username" placeholder="User Name" class="form-control bg-white border-left-0 border-md">-->
                        {{ form.username }}

                    </div>
                    <!--  username errors -->
                    {% for err in form.username.errors %}
                        <div class="input-group col-lg-12 mt-2 ml-1">
                            <span class="form-not-valid"><small>{{ err }}</small></span>
                        </div>
                    {% endfor %}

                    <!-- First Name -->
                    <div class="input-group col-lg-6 mt-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fa fa-user text-muted"></i>
                            </span>
                        </div>
                        {{ form.first_name }}
                    </div>
                    {% for err in form.first_name.errors %}
                         <div class="input-group col-lg-12 mt-2 ml-1">
                            <span class="form-not-valid">
                                <small>{{ err }}</small>
                            </span>
                         </div>
                    {% endfor %}

                    <!-- Last Name -->
                    <div class="input-group col-lg-6 mt-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fa fa-user text-muted"></i>
                            </span>
                        </div>
                        {{ form.last_name }}
                    </div>
                    {% for err in form.last_name.errors %}
                         <div class="input-group col-lg-12 mt-2 ml-1">
                            <span class="form-not-valid">
                                <small>{{ err }}</small>
                            </span>
                         </div>
                    {% endfor %}

                    <!-- Email Address -->
                    <div class="input-group col-lg-12 mt-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fa fa-envelope text-muted"></i>
                            </span>
                        </div>
                        {{ form.email }}
                    </div>
                    {% for err in form.email.errors %}
                         <div class="input-group col-lg-12 mt-2 ml-1">
                            <span class="form-not-valid">
                                <small>{{ err }}</small>
                            </span>
                         </div>
                    {% endfor %}


                    <!-- Password -->
                    <div class="input-group col-lg-6 mt-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fa fa-lock text-muted"></i>
                            </span>
                        </div>
                        {{ form.password1 }}

                    </div>
                    {% for err in form.password1.errors %}
                        <div class="input-group col-lg-12 mt-2 ml-1">
                            <span class="form-not-valid">
                                <small>{{ err }}</small>
                            </span>
                        </div>
                    {% endfor %}

                    <!-- Password Confirmation -->
                    <div class="input-group col-lg-6 mt-4">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-white px-4 border-md border-right-0">
                                <i class="fa fa-lock text-muted"></i>
                            </span>
                        </div>
                        {{ form.password2 }}
                    </div>
                    {% for err in form.password2.errors %}
                        <div class="input-group col-lg-12 mt-2 ml-1">
                            <span class="form-not-valid">
                                <small>{{ err }}</small>
                            </span>
                        </div>
                    {% endfor %}

                    <!-- Submit Button -->
                    <div class="form-group col-lg-12 mx-auto mt-4">
                        <button for="signup_form" type="submit" class="font-weight-bold btn btn-primary btn-block py-2 btn-tyni">Create your account</button>
                    </div>
                </div>
            </form>
            {% endblock %}
        </div>
    </div>
</div>

<script src="{% static 'accounts/js/accounts.js' %}"></script>

</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load generator %}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'images/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- <div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->

    <!-- favicon ends here -->

    {% block page_title %}
    <title>T y n i U R L</title>
    {% endblock %}

    <!-- bootstrap@5.0 cdn -->
        <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous"
        />
        <!-- jQuery and Bootstrap Bundle (includes Popper) -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
            integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
            integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
            crossorigin="anonymous"
        ></script>

    <!-- jQuery CDN -->
    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
    
    {% block custom_css %}
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/home-pg-style.css' %}">
    {% endblock %}
</head>
<body>
  {% block content %}
    <div>
      <nav class="container home-page-nav">
        <div class="brand-name">
          <a href="{% url 'home' %}" class="nav-links btn btn-primary nav-btn">TyniURL</a>
        </div>
        <ul class="nav-items">
          <li>
            <a href="{% url 'about' %}" class="btn btn-primary nav-btn">About</a>
          </li>
          {% if user.is_superuser %}
          <li>
            <a href="{% url 'admin:index' %}" class="btn btn-primary nav-btn">Admin</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'accounts:logout' %}" class="btn btn-primary nav-btn">Log Out</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'accounts:login' %}" class="btn btn-primary nav-btn">login</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
    
    <!-- main body -->
    <div class="content">
      <div class="card" style="width: 40%;">
        <img src="{% static 'images/wallpaper.jpg' %}" class="card-img-top" alt="wallpaper">
        <div class="card-body">
          <div class="card-text">
            {% if user.is_authenticated %}
              <form action="" method="POST" id="user-post-form">
                {% csrf_token %}
                <div class="input-group mb-3">
                <input type="text" class="form-control" name="link" id="link" placeholder="E N T E R - L I N K" aria-label="Long Link" aria-describedby="button-addon">
                <button class="btn btn-outline-primary customize-btn" type="submit" id="button-addon">SHORTEN</button>
                </div>
              </form>
            {% else %}
              <form id="post-form">
                  {% csrf_token %}
                  <div class="input-group mb-3">
                  <input type="text" class="form-control" name="link" id="link" placeholder="E N T E R - L I N K" aria-label="Long Link" aria-describedby="button-addon">
                  <button class="btn btn-outline-primary customize-btn" type="submit" id="button-addon">SHORTEN</button>
                  </div>
              </form>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="card" style="width: 85%;">
        <div class="card-body">
          <div class="table-responsive">
            <section class="shorten-links">
              <h6 class="short-link">New link: <a href="#" target="_blank" id="recent"></a></h6>
            </section>
            {% if user.is_authenticated %}
              <table class="table table-striped table-hover table-fixed">
                <thead>
                  <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Actual Link</th>
                    <th scope="col">Short Link</th>
                    <th scope="col">Copy Link</th>
                  </tr>
                </thead>
                <tbody>
                  {% for new_url in user_urls reversed %}
                    <tr class="text-center">
                      {% with sl_no=user_sl|gen %}
                      <td scope="row">{{ sl_no }}</td>
                      <td><a href="" class="longLink">{{ new_url.link|genshortlen }}</a></td>
                      <td><a href="https://ur9.herokuapp.com/g/{{ new_url.uuid }}" target="_blank" class="shortLink" id="link{{ sl_no }}">ur9.herokuapp.com/g/{{ new_url.uuid }}</a></td>
                      <td>
                        <div
                          class="clicktocopy"
                          onmouseout="outFunc()"
                          id="row{{ sl_no }}"
                        >
                          <img 
                            src="{% static 'images/icons/link.svg' %}" 
                            alt="link-logo" 
                            class="copy-link-ico"
                          />
                          <!-- <span class="tooltiptext" id="tooltip{{ sl_no }}">Click To Copy</span> -->
                        </div>
                      </td>
                      {% endwith %}
                      <!-- <div>Icons made by <a href="https://www.flaticon.com/authors/cursor-creative" title="Cursor Creative">Cursor Creative</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% else %}
              <table class="table table-striped table-hover table-fixed">
                <thead>
                  <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Actual Link</th>
                    <th scope="col">Short Link</th>
                    <th scope="col">Copy Link</th>
                  </tr>
                </thead>
                <tbody>
                  {% for new_url in urls reversed %}
                    <tr class="text-center">
                      {% with sl_no=sl|gen %}
                      <td scope="row">{{ sl_no }}</td>
                      <td><a href="" class="longLink">{{ new_url.link|genshortlen }}</a></td>
                      <td><a href="https://ur9.herokuapp.com/go/{{ new_url.uuid }}" target="_blank" class="shortLink" id="link{{ sl_no }}">ur9.herokuapp.com/go/{{ new_url.uuid }}</a></td>
                      <td>
                        <div
                        class="clicktocopy"
                        onmouseout="outFunc()"
                        id="row{{ sl_no }}"
                        >
                          <img 
                          src="{% static 'images/icons/link.svg' %}" 
                          alt="link-logo" 
                          class="copy-link-ico"
                          />
                          <!-- <span class="tooltiptext" id="tooltip{{ sl_no }}">Click To Copy</span> -->
                        </div>
                      </td>
                      {% endwith %}
                      <!-- <div>Icons made by <a href="https://www.flaticon.com/authors/cursor-creative" title="Cursor Creative">Cursor Creative</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% endif %}
            
          </div>
        </div>
      </div>
    </div>

  <script src="{% static 'js/app.js' %}"></script>
  
  {% endblock %}
</body>
</html>